name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build avec Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: buildozer -v android debug
        repository_root: .

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: package-apk
        path: bin/*.apk
